export const CANCHAS_CREATE_FAIL = 'canchas/CANCHAS_CREATE_FAIL'
export const CANCHAS_CREATE_REQUEST = 'canchas/CANCHAS_CREATE_REQUEST'
export const CANCHAS_CREATE_SUCCESS = 'canchas/CANCHAS_CREATE_SUCCESS'

export const CANCHAS_LIST_FAIL = 'canchas/CANCHAS_LIST_FAIL'
export const CANCHAS_LIST_REQUEST = 'canchas/CANCHAS_LIST_REQUEST'
export const CANCHAS_LIST_SUCCESS = 'canchas/CANCHAS_LIST_SUCCESS'

export const CANCHAS_UPDATE_FAIL = 'canchas/CANCHAS_UPDATE_FAIL'
export const CANCHAS_UPDATE_REQUEST = 'canchas/CANCHAS_UPDATE_REQUEST'
export const CANCHAS_UPDATE_SUCCESS = 'canchas/CANCHAS_UPDATE_SUCCESS'

export const CANCHAS_DELETE_FAIL = 'canchas/CANCHAS_DELETE_FAIL'
export const CANCHAS_DELETE_REQUEST = 'canchas/CANCHAS_DELETE_REQUEST'
export const CANCHAS_DELETE_SUCCESS = 'canchas/CANCHAS_DELETE_SUCCESS'

export const CANCHAS_SELECT_DAY = "canchas/SELECT_DAY"
